//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetBuilder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class BuilderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BuilderSettings defaultInstance = ((BuilderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BuilderSettings())));
        
        public static BuilderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Saves\\")]
        public string PlanetSave {
            get {
                return ((string)(this["PlanetSave"]));
            }
            set {
                this["PlanetSave"] = value;
            }
        }
    }
}
